# Generated by Django 5.1.5 on 2025-01-29 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_full_name', models.CharField(max_length=250)),
                ('bill_email', models.CharField(max_length=250)),
                ('bill_address1', models.CharField(max_length=250)),
                ('bill_address2', models.CharField(max_length=250)),
                ('bill_postcode', models.CharField(max_length=250)),
                ('bill_country', models.CharField(max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Address',
            },
        ),
    ]
