# Generated by Django 5.1.5 on 2025-01-29 02:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='ShippingAddress',
        ),
    ]
