# Generated by Django 5.1.5 on 2025-01-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromatica', '0002_alter_category_options_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
