name: Django CI/CD Pipeline for Aromatica

on:
  push:
    branches:
      - main
jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test

      - name: Deploy to Render
        run: |
          curl -X POST ${{secrets.RENDER_DEPLOY_HOOK_URL }}

      - name: Wait for Render to deploy
        run: sleep 60

      - name: See if site is reachable
        run: |
          echo "checking if site is reachable"
          curl -I https://aromatica-kkpf.onrender.com

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://aromatica-kkpf.onrender.com'
          fail_action: false
          cmd_options: '--config api.disablekey=true -J report_json.json -w report_md.md -r report_html.html'
